CREATE TABLE Country(id_country NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                     country_name VARCHAR2(150));

CREATE TABLE Use_License(id_license NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                         license_type VARCHAR2(150));
CREATE TABLE Image(id_image NUMBER GENERATED ALWAYS AS IDENTITY,
                   id_owner NUMBER NOT NULL,
                   "date" DATE,
                   fk_id_coordinates NUMBER NOT NULL,
                   fk_license_id NUMBER NOT NULL,
                   URL VARCHAR2(500), FOREIGN KEY (id_owner) REFERENCES PERSON,
                   FOREIGN KEY(fk_id_coordinates) REFERENCES GPS_Coordinates,
                   FOREIGN KEY(fk_license_id) REFERENCES Use_License);



CREATE TABLE PERSON(id_person NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    fk_id_country NUMBER,
                    first_name VARCHAR2(150),
                    last_name1 VARCHAR2(150),
                    last_name2 VARCHAR2(150),
                    email VARCHAR2(150),
                    FOREIGN KEY (fk_id_country) REFERENCES COUNTRY,
                    direccion VARCHAR2(450));


CREATE TABLE USUARIO(id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                     fk_person_id NUMBER NOT NULL,
                     FOREIGN KEY (fk_person_id) REFERENCES PERSON);

CREATE TABLE Observation(
                            observation_id NUMBER GENERATED AS IDENTITY PRIMARY KEY,
                            fk_id_taxon NUMBER NOT NULL,
                            fk_id_observer NUMBER NOT NULL,
                            fk_id_coordinates NUMBER NOT NULL,
                            date DATE NOT NULL,
                            comment VARCHAR2(500),
                            fk_id_image NUMBER NOT NULL);

CREATE TABLE Taxonomia(
                          id_taxonomy NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          Name VARCHAR2(100),
                          id_ancestor NUMBER,
                          PRIMARY KEY(id_taxonomy)
);

drop table Taxonomia;
/*
     Reino: Plantae
    Filo: Angiospermas (Magnoliophyta)
    Clase: Eudicotiledóneas (Magnoliopsida)
    Orden: Asterales
    Familia: Asteráceas (Compuestas)
    Género: Helianthus
    Nombre Científico: Helianthus annuus
    Nombre común: Girasol
 */
 -- consulta por jerarquía
SELECT Name, SYS_CONNECT_BY_PATH(Name,'\') "Hierarchy" FROM TAXONOMIA
START WITH id_ancestor = 0 CONNECT BY PRIOR ID_TAXONOMY = id_ancestor
ORDER BY LEVEL;

select * from Taxonomia;

-- Reinos
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Plantae', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Animalia', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Fungi', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Protista', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Archaea/Archaebacteria', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Bacteria/Eubacteria', 0);

--Filos
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Chordata', 2); --ID: 7 -  apunta a Animalia

-- Clases
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Mammalia', 7); --ID: 8 - apunta a Chordata (filo)

-- Órdenes
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Rodentia', 8); --ID: 9 - apunta a Mammalia (clase)

-- Especie: Jaculus Orientalis (Jerbo)
/*
Reino:	Animalia
Filo:	Chordata
Clase:	Mammalia
Orden:	Rodentia
Familia:	Dipodidae
Género:	Jaculus
Especie:	J. orientalis
*/
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Dipodidae', 9); --ID: 10 - apunta a Rodentia (Orden)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jaculus', 10); --ID: 11 - apunta a Dipodidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jaculus Orientalis', 11); --ID: 12 - apunta a Jaculus (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jerbo', 12); --ID: 13 - apunta a Jaculus Orientalis (nombre científico)

-- Especie: Zapus Hudsonius (Ratón Saltarín de las Praderas)
/*
Reino:	Animalia
Filo:	Chordata
Clase:	Mammalia
Orden:	Rodentia
Familia:	Dipodidae
Género:	Zapus
Especie:	Zapus hudsonius
 */
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Zapus', 10); --ID: 14 - apunta a Dipodidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Zapus Hudsonius', 14); --ID: 15 - apunta a Zapus (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Ratón Saltarín de las Praderas', 15); --ID: 16 - apunta a Zapus Hudsonius (nombre científico)

-- Especie: PUercoespín arborícola
/*
 Reino:	Animalia
Filo:	Chordata
Clase:	Mammalia
Orden:	Rodentia
Familia:	Erethizontidae
Género:	Coendou
Especie:	C. prehensilis
 */
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Erethizontidae', 9); --ID: 17 - apunta a Rodentia (Orden)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Coendou', 17); --ID: 18 - apunta a Erethizontidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Coendou Prehensilis', 18); --ID: 19 - apunta a Coendou (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Puercoespín Arborícola', 19); --ID: 20 - apunta a Coendou Prehensilis (nombre científico)


--Capibara
/*
 Reino:	Animalia
Filo:	Chordata
Clase:	Mammalia
Orden:	Rodentia
Familia:	Caviidae
Género:		Hydrochoerus
Especie:	H. hydrochaeris
 */
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Caviidae', 9); --ID: 21 - apunta a Rodentia (Orden)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hydrochoerus', 21); --ID: 22 (apunta a Cavidae)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hydrochoerus Hydrochaeris', 22); --ID: 23 (apunta a Hydrochoerus)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Capibara', 23); --ID: 24 (apunta a Hydrochoerus hydrochaeris)



/*
--Especie: pajaro cuco
Reino:	Animalia
Filo:	Chordata
Clase:	Aves
Orden:	Cuculiformes
Familia:	Cuculidae
Género: Cuculus
Nombre común: Cuco común
Nombre cientifico:Cuculus canorus
*/

INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Aves', 7); --ID: 25 - apunta a Chordata (filo)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculiformes', 25); --ID: 26 - apunta a Aves
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculidae', 26); --ID: 27 - apunta a Cuculiformes
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculus', 27); --ID: 28 - apunta a Cuculidae
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculus canorus', 28); --ID: 29 - apunta a Cuculus
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuco común', 29); --ID: 30 - apunta a Cuculus canorus

/*
Reino:	Fungi
Filo:	Ascomycota
Clase:	Sordariomycetes
Orden:	Hypocreales
Familia:	Ophiocordycipitaceae
Género:	Ophiocordyceps
Especie:	O. unilateralis
(Tul.) Petch (1931)
 */
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ascomycota', 3); -- ID: 31 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Sordariomycetes', 31); -- ID: 32 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hypocreales', 32); -- ID: 33 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordycipitaceae', 33); -- ID: 34 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordyceps', 34); -- ID: 35 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordyceps unilateralis', 35); -- ID: 36 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hongo Zombi', 36); -- ID: 37 apunta a fungi

/*
Reino:	Animalia
Filo:	Mollusca
Clase:	Cephalopoda
Orden:	Teuthida
Familia:	Architeuthidae
Pfeffer, 1900
Género:	Architeuthis
 */
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Mollusca', 2); -- ID: 38 apunta a Animalia
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Cephalopoda', 38); -- ID: 39 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Teuthida', 39); -- ID: 40 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthidae', 40); -- ID: 41 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthis', 41); -- ID: 42 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthis dux', 42); -- ID: 43 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Calamar gigante del Atlántico', 43); -- ID: 44 apunta a fungi