
CREATE SEQUENCE coord_sequence
    START WITH 1
    INCREMENT BY 1
    CACHE 5;

CREATE TABLE GPS_Coordinates(id_coordinates NUMBER NOT NULL PRIMARY KEY,
                             latidude VARCHAR2(50),
                             longitude VARCHAR2(50));

CREATE TABLE Country(id_country NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                     country_name VARCHAR2(150));

CREATE TABLE Use_License(id_license NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                         license_type VARCHAR2(150));


CREATE SEQUENCE image_sequence
    START WITH 1
    INCREMENT BY 1
    CACHE 5;
CREATE TABLE Image(id_image NUMBER NOT NULL PRIMARY KEY,
                   id_owner NUMBER NOT NULL,
                   date_ DATE,
                   fk_id_coordinates NUMBER NOT NULL,
                   fk_license_id NUMBER NOT NULL,
                   URL VARCHAR2(500),
                   FOREIGN KEY (id_owner) REFERENCES PERSON,
                   FOREIGN KEY(fk_id_coordinates) REFERENCES GPS_Coordinates,
                   FOREIGN KEY(fk_license_id) REFERENCES Use_License);




CREATE TABLE PERSON(id_person NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    fk_id_country NUMBER,
                    first_name VARCHAR2(150),
                    last_name1 VARCHAR2(150),
                    last_name2 VARCHAR2(150),
                    email VARCHAR2(150),
                    FOREIGN KEY (fk_id_country) REFERENCES COUNTRY,
                    direccion VARCHAR2(450));


CREATE TABLE USUARIO(id_usuario NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                     fk_person_id NUMBER NOT NULL,
                     FOREIGN KEY (fk_person_id) REFERENCES PERSON);

CREATE TABLE Taxonomia(
                          id_taxonomy NUMBER GENERATED BY DEFAULT AS IDENTITY,
                          Name VARCHAR2(100),
                          id_ancestor NUMBER,
                          PRIMARY KEY(id_taxonomy)
);


CREATE TABLE Observation(
                            observation_id NUMBER GENERATED AS IDENTITY PRIMARY KEY,
                            fk_id_taxon NUMBER NOT NULL,
                            fk_id_observer NUMBER NOT NULL,
                            fk_id_coordinates NUMBER NOT NULL,
                            date_ DATE NOT NULL,
                            comment_ VARCHAR2(500),
                            fk_id_image NUMBER NOT NULL,
                            FOREIGN KEY(fk_id_taxon) REFERENCES TAXONOMIA,
                            FOREIGN KEY(fk_id_observer) REFERENCES USUARIO,
                            FOREIGN KEY(fk_id_coordinates) REFERENCES GPS_Coordinates);




-- prueba de observación
-- debe existir la referencia en: Taxonomia, Usuario, Coordenadas, e Imagen

INSERT INTO GPS_COORDINATES(id_coordinates, latidude, longitude) VALUES (coord_sequence.nextval, '31.20421226393401', '29.94574961570779'); -- Zoológico de Alejandría
INSERT INTO IMAGE(id_image,id_owner, date_, fk_id_coordinates, fk_license_id, URL) VALUES (image_sequence.nextval, 1, TO_DATE('05/07/2001', 'DD/MM/YYYY'), 1, 1, 'C:\Users\Public\iNaturalist\JaculusOrientalis.jpg');

insert into Observation (fk_id_taxon, fk_id_observer, fk_id_coordinates, date_, comment_, fk_id_image) VALUES (13, 1, 1, TO_DATE('05/07/2001', 'DD/MM/YYYY'), 'Miren qué lindo', 1);
insert into Observation (fk_id_taxon, fk_id_observer, fk_id_coordinates, date_, comment_, fk_id_image) VALUES (30, 1, 1, TO_DATE('05/07/2020', 'DD/MM/YYYY'), 'Avistado en el desierto', 1);


INSERT INTO PERSON( FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40,'Alejandro', 'Quesada', 'Calderón', 'alejosequesada@gmail.com','125m Oeste del Estadio Municipal Allen Rigionni, Grecia, Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40, 'Bryan', 'Castro', 'Madrigal', 'bryancastromadrigal@gmail.com', 'Giralda Desamparados Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40, 'Annette', 'Morúa', 'Rodriguez', 'morúarodriguez@hotmail.com', 'Agua Clara, Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40, 'Eithan', 'Rivera', 'Rivera', 'eithanrivera@yahoo.com', 'Rio segundo Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40, 'Celeste', 'Fonseca', 'Perez', 'celestefonse@gmail.com', 'San Rafael Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (109, 'Ricardo', 'Noverola', 'Sanchez', 'noverolarichar@gmail.com', 'Tabasco'); --mexicano
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (186, 'Valeria', 'Ogletree', 'Ocampo', 'Ogletree@gmail.com', 'Winsconsin'); --gringo
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (35, 'Germán', 'Garmendia', 'Aranis', 'holasoygerman@gmail.com', 'Copiapó'); -- chileno
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (142, 'Nathan', 'Drake', 'Marston', 'Marston@gmail.com', 'Rusia');--Ruso
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (40, 'Joshua', 'Solís', 'Fuentes', 'joshuasolisfuentes@gmail.com', 'Urbanización Alicante Desamparados Alajuela');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (81, 'Michele', 'Rech', 'Fernandez', 'zerocalcare@gmail.com', 'Cortona');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (186, 'George', 'Lucas', 'Junior', 'lucasfilm@hotmail.com', 'California');
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (186, 'Joel', 'Miller', 'Williams', 'Joelmiller@hotmail.com', 'Jackson, Wyoming'); -- mejor jackson :v en wyoming
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (81, 'Ezio', 'Auditore', 'Firenze', 'ezioauditore@gmail.com', 'Venecia'); -- italia
INSERT INTO PERSON (FK_ID_COUNTRY, FIRST_NAME, LAST_NAME1, LAST_NAME2, EMAIL, DIRECCION) VALUES (186, 'George', 'Lucas', 'Junior', 'lucasfilm@hotmail.com', 'California');

INSERT INTO USUARIO (FK_PERSON_ID) VALUES (1);

INSERT INTO USUARIO (FK_PERSON_ID) VALUES (10);
INSERT INTO USUARIO (FK_PERSON_ID) VALUES (15);

-- Reinos
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Plantae', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Animalia', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Fungi', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Protista', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Archaea/Archaebacteria', 0);
INSERT INTO Taxonomia(Name, id_ancestor) VALUES ('Bacteria/Eubacteria', 0);

--Filos
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Chordata', 2); --ID: 7 -  apunta a Animalia

-- Clases
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Mammalia', 7); --ID: 8 - apunta a Chordata (filo)

-- Órdenes
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Rodentia', 8); --ID: 9 - apunta a Mammalia (clase)


INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Dipodidae', 9); --ID: 10 - apunta a Rodentia (Orden)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jaculus', 10); --ID: 11 - apunta a Dipodidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jaculus Orientalis', 11); --ID: 12 - apunta a Jaculus (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Jerbo', 12); --ID: 13 - apunta a Jaculus Orientalis (nombre científico)

INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Zapus', 10); --ID: 14 - apunta a Dipodidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Zapus Hudsonius', 14); --ID: 15 - apunta a Zapus (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Ratón Saltarín de las Praderas', 15); --ID: 16 - apunta a Zapus Hudsonius (nombre científico)

INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Erethizontidae', 9); --ID: 17 - apunta a Rodentia (Orden)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Coendou', 17); --ID: 18 - apunta a Erethizontidae (Familia)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Coendou Prehensilis', 18); --ID: 19 - apunta a Coendou (Género)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Puercoespín Arborícola', 19); --ID: 20 - apunta a Coendou Prehensilis (nombre científico)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Caviidae', 9); --ID: 21 - apunta a Rodentia (Orden)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hydrochoerus', 21); --ID: 22 (apunta a Cavidae)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hydrochoerus Hydrochaeris', 22); --ID: 23 (apunta a Hydrochoerus)

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Capibara', 23); --ID: 24 (apunta a Hydrochoerus hydrochaeris)


INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Aves', 7); --ID: 25 - apunta a Chordata (filo)
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculiformes', 25); --ID: 26 - apunta a Aves
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculidae', 26); --ID: 27 - apunta a Cuculiformes
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculus', 27); --ID: 28 - apunta a Cuculidae
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuculus canorus', 28); --ID: 29 - apunta a Cuculus
INSERT INTO TAXONOMIA(Name, id_ancestor) VALUES ('Cuco común', 29); --ID: 30 - apunta a Cuculus canorus

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ascomycota', 3); -- ID: 31 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Sordariomycetes', 31); -- ID: 32 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hypocreales', 32); -- ID: 33 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordycipitaceae', 33); -- ID: 34 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordyceps', 34); -- ID: 35 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Ophiocordyceps unilateralis', 35); -- ID: 36 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Hongo Zombi', 36); -- ID: 37 apunta a fungi

INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Mollusca', 2); -- ID: 38 apunta a Animalia
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Cephalopoda', 38); -- ID: 39 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Teuthida', 39); -- ID: 40 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthidae', 40); -- ID: 41 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthis', 41); -- ID: 42 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Architeuthis dux', 42); -- ID: 43 apunta a fungi
INSERT INTO Taxonomia(Name, id_ancestor) VALUES('Calamar gigante del Atlántico', 43); -- ID: 44 apunta a fungi



-- consulta por jerarquía
SELECT Name, SYS_CONNECT_BY_PATH(Name,'\') "Hierarchy" FROM TAXONOMIA
START WITH id_ancestor = 0 CONNECT BY PRIOR ID_TAXONOMY = id_ancestor
ORDER BY LEVEL;

select * from Taxonomia;

select * from GPS_Coordinates;
-- chile: 35, USA: 186, Italia: 81, Rusia: 142, Mexico: 109
select * from COUNTRY;
select * from USE_LICENSE;
select * from person;
select * from USUARIO;
select * from Observation;
-- función para obtener la jerarquía de todas las observaciones
WITH Hierarchy AS (
    SELECT id_taxonomy, name, SYS_CONNECT_BY_PATH(Name, '\') AS Path
        FROM TAXONOMIA
        START WITH id_ancestor = 0
        CONNECT BY PRIOR ID_TAXONOMY = id_ancestor
    )
SELECT observation_id, h.Path
    FROM Observation o, Hierarchy h
    WHERE o.fk_id_taxon = h.id_taxonomy;

commit;

